openapi: "3.0.1"
info:
  title: "Eligibility and Enrollment Client"
  version: v1
servers:
  - url: https://localhost:8088/api
    description: Local Instance
paths:
  /v1/eligibilityandenrollment:
    get:
      summary: Send request to EE Service for given parameters
      operationId: eeRequest
      parameters:
      - in: query
        name: id
        description: ICN of a Person
        schema:
          type: string
          pattern: "[0-9]{10,16}V[0-9]{6,12}"
      responses:
        '200':
          description: Eligibility Response
          content:
            application/xml:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  responses:
    BadRequest:
      description:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
        application/xml:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        timestamp:
          type: integer
          format: base64
          description: ms since the epoch
        message:
          type: string
        type:
          type: string
      required:
        - message

